name: Build KSO Ultra

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with: { dotnet-version: '8.0.x' }
    
    - run: dotnet restore KSO.csproj
    - run: dotnet publish KSO.csproj -c Release -r win-x64 --self-contained false -o publish
    
    - run: powershell Compress-Archive -Path publish\* -DestinationPath KSO-Ultra-Portable.zip
    
    - run: |
        powershell curl -L https://jrsoftware.org/download.php/inno-setup.exe -o inno.exe
        powershell .\inno.exe /VERYSILENT
    
    - run: |
        powershell mkdir setup_files
        powershell xcopy publish\* setup_files\ /E /Y
        powershell xcopy app.ico setup_files\ /Y
        powershell xcopy *.json setup_files\ /Y
        powershell xcopy Modules setup_files\Modules\ /E /Y
        powershell xcopy Resources setup_files\Resources\ /E /Y
    
    - run: powershell & "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" setup.iss
    
    - uses: softprops/action-gh-release@v2
      with:
        files: |
          KSO-Ultra-Portable.zip
          Output/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
